#!/usr/bin/env python3
"""Will a signed watch app (.bin) pass the watch installer's checks?

    tools/check-watch-bin.py WatchApps/MyApp.bin

On a failed install the watch only says "103"; this tool tells the most common reasons up front.
The checks follow the rules in OpenHarmony appexecfwk_lite (OpenHarmony-v1.1.1-LTS)
gt_bundle_parser.cpp and gt_bundle_installer.cpp.
"""
import json
import re
import struct
import sys


def entries(data):
    sign = int.from_bytes(data[-12:-8], "big") if data[-32:-16] == b"hw signed app   " else 0
    if data[0] != 0xBE:
        raise ValueError("first byte is not 0xBE (not a haptobin output)")
    i = 1
    n = struct.unpack(">I", data[i:i + 4])[0]
    i += 4
    bundle = data[i:i + n].decode()
    i += n
    files = {}
    while len(data) - i > sign:
        n = struct.unpack(">I", data[i:i + 4])[0]
        i += 4
        name = data[i:i + n].decode()
        i += n
        n = struct.unpack(">I", data[i:i + 4])[0]
        i += 4
        path = data[i:i + n].decode()
        i += n
        n = struct.unpack(">Q", data[i:i + 8])[0]
        i += 8
        files[(path + "/" + name) if path else name] = data[i:i + n]
        i += n
    return bundle, files, sign


def check(path):
    data = open(path, "rb").read()
    errors, notes = [], []
    bundle, files, sign = entries(data)
    if not sign:
        errors.append("not signed (hap-sign-tool sign-app -inForm bin)")
    profile = None
    match = re.search(rb'\{"version-name".*?"issuer":"[^"]*"\}', data[-65536:], re.S)
    if match:
        profile = json.loads(match.group(0))
    elif sign:
        errors.append("no profile found in the signature block")

    cfg = json.loads(files["config.json"])
    app, mod = cfg["app"], cfg["module"]
    if app.get("bundleName") != bundle:
        errors.append("config.json bundleName differs from the package header")
    if not 7 <= len(bundle) <= 127:
        errors.append("the package name must be 7-127 characters")
    version = app.get("version", {})
    if not version.get("name") or len(version["name"]) > 20:
        errors.append("version.name is empty or longer than 20 characters")
    if not isinstance(version.get("code"), int) or version["code"] < 0:
        errors.append("version.code is not a number")
    device = mod.get("deviceType") or []
    if not any(d in ("liteWearable", "fitnessWatch") for d in device):
        errors.append(f"deviceType {device}: must contain liteWearable")
    distro = mod.get("distro", {})
    if (not isinstance(distro.get("deliveryWithInstall"), bool) or not distro.get("moduleName")
            or distro.get("moduleType") not in ("entry", "feature")):
        errors.append("module.distro is incomplete (deliveryWithInstall, moduleName, moduleType)")
    if mod.get("metaData"):
        notes.append("module.metaData is set: fields like 'supportLists' can freeze the app at launch")
    ability = (mod.get("abilities") or [{}])[0]
    label = ability.get("label") or ""
    if label.startswith("$string:") and not isinstance(ability.get("labelId"), int):
        errors.append("labelId missing (the config.json generated by restool must be used)")
    if len(label) > 30:
        errors.append("label is longer than 30 characters")
    if ability.get("icon") != "$media:icon":
        errors.append('icon must be "$media:icon"')
    if not isinstance(ability.get("iconId"), int) or ability["iconId"] <= 0:
        errors.append("iconId missing")
    media = f"/assets/{distro.get('moduleName', 'entry')}/resources/base/media"
    for icon in ("icon.bin", "icon_small.bin"):
        if f"{media}/{icon}" not in files:
            png = icon.replace(".bin", ".png")
            errors.append(f"{media}/{icon} missing -> add resources/base/media/{png} (the most common cause of 103)")
    if not any(k.startswith("/assets/js/default") for k in files):
        errors.append("assets/js/default missing")

    if profile:
        info = profile.get("bundle-info", {})
        if info.get("bundle-name") != bundle:
            errors.append(f"the profile's package ({info.get('bundle-name')}) does not match the app")
        devices = profile.get("debug-info", {}).get("device-ids", [])
        notes.append(f"profile: {profile.get('type')}, {len(devices)} device UDID(s) (your watch's UDID must be one of them)")
    return bundle, errors, notes


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    failed = False
    for path in sys.argv[1:]:
        bundle, errors, notes = check(path)
        print(f"{path} ({bundle})")
        for note in notes:
            print("  note:", note)
        for error in errors:
            print("  ERROR:", error)
        print("  RESULT:", "OK" if not errors else "WILL NOT INSTALL")
        failed |= bool(errors)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
